namespace FID.Models
{
    public class MunicipalityData
    {
        public static Dictionary<string, KeyValuePair<string, List<string>>> NovadiUnPilsetas { get; } = new Dictionary<string, KeyValuePair<string, List<string>>>()
        {
 
            {"Rīga", new KeyValuePair<string, List<string>>("0001000", new List<string> {"Rīga"})},
            {"Jūrmala", new KeyValuePair<string, List<string>>("0004000", new List<string> {"Jūrmala"})},
            {"Liepāja", new KeyValuePair<string, List<string>>("", new List<string> {"Liepāja"})},
            {"Ventspils", new KeyValuePair<string, List<string>>("0007000", new List<string> {"Ventspils"})},
            {"Jelgava", new KeyValuePair<string, List<string>>("0003000", new List<string> {"Jelgava"})},
            {"Rēzekne", new KeyValuePair<string, List<string>>("", new List<string> {"Rēzekne"})},
            {"Jēkabpils", new KeyValuePair<string, List<string>>("0031010", new List<string> {"Jēkabpils"})},
            {"Visi", new KeyValuePair<string, List<string>>("0000000", new List<string> {"Visi"})},
            {"Salaspils", new KeyValuePair<string, List<string>>("", new List<string> {"Salaspils"})},
            {"Mārupe", new KeyValuePair<string, List<string>>("", new List<string> {"Mārupe"})},
            {"Tukums", new KeyValuePair<string, List<string>>("", new List<string> {"Tukums"})},
            {"Cēsis", new KeyValuePair<string, List<string>>("", new List<string> {"Cēsis"})},
            {"Sigulda", new KeyValuePair<string, List<string>>("", new List<string> {"Sigulda"})},
            {"Olaine", new KeyValuePair<string, List<string>>("", new List<string> {"Olaine"})},
            {"Kuldīga", new KeyValuePair<string, List<string>>("", new List<string> {"Kuldīga"})},
            {"Bauska", new KeyValuePair<string, List<string>>("", new List<string> {"Bauska"})},
            {"Saldus", new KeyValuePair<string, List<string>>("", new List<string> {"Saldus"})},
            {"Talsi", new KeyValuePair<string, List<string>>("", new List<string> {"Talsi"})},
            {"Daugavpils", new KeyValuePair<string, List<string>>("0002000", new List<string> {"Daugavpils"})},
            {"Ādažu novads", new KeyValuePair<string, List<string>>("0023000", new List<string> { "Ādaži", "Carnikava", "Kadaga", "Garciems", "Gauja", "Kalngale", "Baltezers", "Garupe", "Staprini", "Alderi", "Siguļi", "Atari" })},
            {"Aizkraukles novads", new KeyValuePair<string, List<string>>("0020000", new List<string> { "Aizkraukle", "Plavinas", "Koknese", "Skriveri", "Jaunjelgava", "Nereta", "Daudzeva", "Vecbebri", "Zemkopibas institat", "Aizkraukle (ciems)", "Sece", "Irsi", "Èrberde", "Serene" })},
            {"Alūksnes novads", new KeyValuePair<string, List<string>>("0021000", new List<string> { "Alūksne", "Liepna", "Jaunanna", "Alsviki", "Kolbergis", "Jaunlaicene", "Malupe", "Strautini", "Marinkalns", "Zeltini", "Anna", "Brenci", "Jaunzemi", "Korneti", "Markalne", "Pededze", "Sofikains", "Kalncempji", "Ziemeri" })},
            {"Augšdaugavas novads", new KeyValuePair<string, List<string>>("0022000", new List<string> { "Ilūkste", "Vecstropi", "Lociki", "Krauja", "Kalkūni", "Višķi", "Subate", "Silene", "Kalupe", "Medumi", "Svente", "Randene", "Bebrene", "Eglaine", "Mirnijs", "Naujene", "Nicgale", "Dubna", "Malinova", "Pasuliene", "Demene", "Kumbuli", "Tabore", "Ambeli", "Spogi", "Dviete", "Sedere", "Saliena", "Červonka", "Liksna", "Vabole", "Biķernieki", "Laucesa", "Pilskalne", "Skrudaliena", "Vīganti", "Stropi", "Muitas" })},
            {"Balvu novads", new KeyValuePair<string, List<string>>("0024000", new List<string> { "Balvi", "Viļaka", "Žīguri", "Tilza", "Baltinava", "Kubuli", "Kuprava", "Semenova", "Vīksna", "Bērzpils", "Bērzkalne", "Šķilbēni", "Rekova", "Borisova", "Naudaskalns", "Krisiani", "Egļuciems", "Vectilža", "Briežuciems", "Balvu rajons" })},
            {"Bauskas novads", new KeyValuePair<string, List<string>>("0025000", new List<string> { "Bauska", "Iecava", "Vecumnieki", "Rītausmas", "Uzvara", "Bērzkalni", "Pilsrundāle", "Misa", "Skaistkalne", "Code" })},
            {"Cēsu novads", new KeyValuePair<string, List<string>>("0026000", new List<string> { "Cēsis", "Liepa", "Priekuli", "Augšlīgatne", "Līgatne", "Jaunpiebalga", "Jāņmuiža", "Dzērbene", "Vecpiebalga", "Straupe", "Līvi", "Cēsu rajons", "Cēsu raj" })},
            {"Dienvidkurzemes novads", new KeyValuePair<string, List<string>>("0027000", new List<string> { "Aizpute", "Grobiņa", "Priekule", "Vaiņode", "Nica", "Pāvilosta", "Kazdanga", "Durbe", "Rucava", "Kapsēde" })},
            {"Dobeles novads", new KeyValuePair<string, List<string>>("0028000", new List<string> { "Dobele", "Auce", "Bēne", "Gardene", "Jaunbērzē", "Miltiņi", "Augstkalne", "Kroņauce", "Vecauce", "Kaķenieki" })},
            {"Gulbenes novads", new KeyValuePair<string, List<string>>("0029000", new List<string> { "Gulbene", "Litene", "Lizums", "Stāķi", "Ranka", "Lejasciems", "Jaungulbene", "Šķieneri", "Stari", "Vecstāmeriena" })},
            {"Jēkabpils novads", new KeyValuePair<string, List<string>>("0031000", new List<string> { "Jekabpils", "Viesīte", "Sala", "Aknīste", "Birži", "Brodi", "Zasa", "Mežāre", "Zilāni", "Jaunā muiša" })},
            {"Jelgavas novads", new KeyValuePair<string, List<string>>("0030000", new List<string> { "Ozolnieki", "Kalnciems", "Eleja", "Áne", "Brankas", "LIvberze", "Nakotne", "Svête", "Zalenieki", "Mezciems" })},
            {"Krāslavas novads", new KeyValuePair<string, List<string>>("0032000", new List<string> { "Kraslava", "Dagda", "Indra", "Augstkalne", "Ezernieki", "Andrupene", "Skaune", "Robeznieki", "Andzeli", "Asone" })},
            {"Kuldīgas novads", new KeyValuePair<string, List<string>>("0033000", new List<string> { "Kuldiga", "Skrunda", "Priedaine", "Alsunga", "Varme", "Pelci", "Édole", "Mezvalde", "Rudbarzi", "Kabile" })},
            {"Ķekavas novads", new KeyValuePair<string, List<string>>("0034000", new List<string> { "Balozi", "Kekava", "Baldone", "Katlakalns", "Valdlauci", "Ramava", "Odukalns", "Krustkalni", "Dzèrumi", "Vimbukrogs" })},
            {"Limbažu novads", new KeyValuePair<string, List<string>>("0035000", new List<string> { "Limbaži", "Salacgriva", "Aloja", "Staicele", "Skulte", "Ainazi", "Ozolaine", "Umurga", "Vilkene", "Svetciems","Limbažu rajons" })},
            {"Līvānu novads", new KeyValuePair<string, List<string>>("0036000", new List<string> { "Livani", "Rudzati", "Rozupe", "Sutri", "Upiniki", "Jaunsilavas", "Jersika", "Turki" })},
            {"Ludzas novads", new KeyValuePair<string, List<string>>("0037000", new List<string> { "Ludza", "Karsava", "Zilupe", "Malnava", "Martisi", "Pasiene", "Tutani", "Merdzene", "Pilda", "Vecslabada" })},
            {"Madonas novads", new KeyValuePair<string, List<string>>("0038000", new List<string> { "Madona", "Ergli", "Lubana", "Cesvaine", "Barkava", "Jaunkalsnava", "Marciena", "Laudona", "Kusa", "Lazdona" })},
            {"Mārupes novads", new KeyValuePair<string, List<string>>("0039000", new List<string> { "Marupe", "Pinki", "Jaunmarupe", "Tiraine", "Spilve", "Mezares", "Babite", "Skulte", "Spunciems", "Vetras" })},
            {"Ogres novads", new KeyValuePair<string, List<string>>("0040000", new List<string> { "Ogre", "Ikšķile", "Lielvārde", "Kegums", "Ciemupe", "Ogresgals", "Jumprava", "Madliena", "Suntazi", "Tinazi" })},
            {"Olaines novads", new KeyValuePair<string, List<string>>("0041000", new List<string> { "Olaine", "Jaunolaine", "Medemciems", "Stonisi", "Janupe", "Parolaine", "Grênes", "Virsi", "Peternieki", "Stipnieki" })},
            {"Preiļu novads", new KeyValuePair<string, List<string>>("0042000", new List<string> { "Preiļi", "Agiona", "Riebini", "LICI", "Galêni", "Stabulnieki", "Prikuli", "Kastire", "Peleci", "Jaunagiona", "Preiļu rajons" })},
            {"Rēzeknes novads", new KeyValuePair<string, List<string>>("0006000", new List<string> { "Vilani", "Malta", "Pleiksni", "Strozani", "Kaunata", "Audrini", "Sondori", "Vecruzina", "Sprazeva" })},
            {"Ropažu novads", new KeyValuePair<string, List<string>>("0044000", new List<string> { "Vangazi", "Ulbroka", "Dreilini", "Garkalne", "Sauriesi", "Ropazi", "Bergi", "Upeslejas", "Upesciems", "Dzidrinas" })},
            {"Salaspils novads", new KeyValuePair<string, List<string>>("0045000", new List<string> { "Salaspils", "Saulkalne", "Acone", "Jaunsauriesi", "Mezezeri", "Sauriesi", "Pikalne", "Silabriezi", "Bajari", "Roki" })},
            {"Saldus novads", new KeyValuePair<string, List<string>>("0046000", new List<string> { "Saldus", "Brocēni", "Druva", "Lutrini", "Kalni", "Ezere", "Nigrande", "Kursīši", "Oskalni", "Pampali" })},
            {"Saulkrastu novads", new KeyValuePair<string, List<string>>("0047000", new List<string> { "Saulkrasti", "Zvejniekciems", "Loja", "Pabazi", "VEF-Bikernieki", "Murjani", "Jubileja", "Seja", "Priedes", "Roze" })},
            {"Siguldas novads", new KeyValuePair<string, List<string>>("0048000", new List<string> { "Sigulda", "Incukalns", "Malpils", "Ragana", "Gauja", "Allazi", "Lēdurga", "Inciems", "Sidgunda", "Eglupe" })},
            {"Smiltenes novads", new KeyValuePair<string, List<string>>("0049000", new List<string> { "Smiltene", "Rauna", "Ape", "Palsmane", "Gaujiena", "Varini", "Grundzale", "Silva", "Trapene", "Drusti" })},
            {"Talsu novads", new KeyValuePair<string, List<string>>("0051000", new List<string> { "Talsi", "Roja", "Stende", "Sabile", "Dundaga", "Mersrags", "Valdemarpils", "Lauciene", "Pastende", "Kolka", "Talsu rajons" })},
            {"Tukuma novads", new KeyValuePair<string, List<string>>("0052000", new List<string> { "Tukums", "Kandava", "Engure", "Lapmezciems", "Slampe", "Jaunpils", "Smārde", "Pāre", "Ragaciems", "Tume","Abavnieki", "Tukuma rajons" })},
            {"Valkas novads", new KeyValuePair<string, List<string>>("0053000", new List<string> { "Valka", "Kārķi", "Ērģeme", "Vijciems", "Lugaži", "Sēli", "Štēpi", "Turna" })},
            {"Valmieras novads", new KeyValuePair<string, List<string>>("0054010", new List<string> { "Valmiera", "Rūjiena", "Valmiermuiža", "Seda", "Mazsalaca", "Strenči", "Kocēni", "Zilaiskalns", "Naukšēni", "Rencēni" })},
            {"Varakļānu novads", new KeyValuePair<string, List<string>>("0055000", new List<string> { "Varakļāni", "Murmastiene", "Kokari", "Silagals", "Incērnieki", "Stirniene" })},
            {"Ventspils novads", new KeyValuePair<string, List<string>>("0056000", new List<string> { "Ugāle", "Piltene", "Pope", "Blāzma", "Ventava", "Ance", "Varve", "Zāras", "Zieķi", "Užava" })},
            {"Viesītes novads", new KeyValuePair<string, List<string>>("0057000", new List<string> { "Viesīte", "Elkšņi", "Rite", "Upeslejas", "Sērene", "Zasa" })},
            {"Viļakas novads", new KeyValuePair<string, List<string>>("0058000", new List<string> { "Viļaka", "Šķilbēni", "Žīguri", "Medņeva", "Kuprava" })},
            {"Viļānu novads", new KeyValuePair<string, List<string>>("0059000", new List<string> { "Viļāni", "Sokolki", "Dekšāres", "Mori", })},
            {"Ķeguma nov", new KeyValuePair<string, List<string>>("", new List<string> {"Birzgale"})},
            {"Ķekavas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Ķekavas "})},
            {"Stopiņu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Saurieši"})},
            {"Mālpis nov", new KeyValuePair<string, List<string>>("", new List<string> {"Mālpils "})},
            {"Talsu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Roceži"})},
            {"Riebiņu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Riebiņi"})},
            {"Limbažu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Limbaži"})},
            {"Vārkavas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Vecvārkava"})},
            {"Krustpils nov", new KeyValuePair<string, List<string>>("", new List<string> {"Variešu pag"})},
            {"Ropažu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Ropaži"})},
            {"Tērvetes nov", new KeyValuePair<string, List<string>>("", new List<string> {"Zelmeņi"})},
            {"Lubānas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Lubāna"})},
            {"Pārgaujas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Stalbe"})},
            {"Naukšēnu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Naukšēnu pag"})},
            {"Burtnieku nov", new KeyValuePair<string, List<string>>("", new List<string> {"Matīšu pag"})},
            {"Babītes nov", new KeyValuePair<string, List<string>>("", new List<string> {"Priežciems"})},
            {"Skrīveru nov", new KeyValuePair<string, List<string>>("", new List<string> {"Skrīveri"})},
            {"Preiļu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Preiļi"})},
            {"Pļaviņu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Pļaviņas"})},
            {"Inčukalna nov", new KeyValuePair<string, List<string>>("", new List<string> {"Inčukalns"})},
            {"Krāslavas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Krāslava"})},
            {"Dienvidkurzemes nov", new KeyValuePair<string, List<string>>("", new List<string> {"Jūrmalciems"})},
            {"Ērgļu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Ērgļu nov"})},
            {"Beverīnas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Beverīnas nov"})},
            {"Krimuldas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Krimuldas nov"})},
            {"Cēsu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Agra"})},
            {"Rundāles nov", new KeyValuePair<string, List<string>>("", new List<string> {"Rundāles pag"})},
            {"Priekuļu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Priekuļi"})},
            {"Līvānu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Līvāni nov"})},
            {"Augšdaugavas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Līksnas pag"})},
            {"Kocēnu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Dauguļi "})},
            {"Tukuma nov", new KeyValuePair<string, List<string>>("", new List<string> {"Abavnieki"})},
            {"Ādažu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Eimuri nov"})},
            {"Saulkrastu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Sēja"})},
            {"Balvu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Rugāji"})},
            {"Ciblas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Lucmuiža"})},
            {"Vecumnieku nov", new KeyValuePair<string, List<string>>("", new List<string> {"Bārbeles pag"})},
            {"Strenču nov", new KeyValuePair<string, List<string>>("", new List<string> {"Plāņi"})},
            {"Aglonas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Aglona"})},
            {"Brocēnu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Blīdene"})},
            {"Ozolnieku nov", new KeyValuePair<string, List<string>>("", new List<string> {"Salgales pag"})},
            {"Nīcas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Klampju ciems"})},
            {"Kārsavas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Kārsava"})},
            {"Mērsraga nov", new KeyValuePair<string, List<string>>("", new List<string> {"Mērsraga"})},
            {"Amatas nov", new KeyValuePair<string, List<string>>("", new List<string> {"Amatciems "})},
            {"Viļānu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Radopole"})},
            {"Varakļānu nov", new KeyValuePair<string, List<string>>("", new List<string> {"Varakļāni "})},
            {"Rugāju nov", new KeyValuePair<string, List<string>>("", new List<string> {"Lazdukalna pag"})},
            {"Vangaži", new KeyValuePair<string, List<string>>("0044200", new List<string> { "Vangaži" })},
        };
    }
}